### ISSUE TITLE
Re: Usage of new SNPs and Indels with your code

### ISSUE THREAD

**Issue by bharath-cchmc** [hyounesy/ALEA#1]
Will ALEA be able to work with [New SNPs and Indels](http://csbio.unc.edu/CCstatus/index.py?run=Pseudo)?

@hyounesy

**Comment by hyounesy** [comment]
I have not tried it myself, but in principle, it should work fine as long as the variants are in the vcf format and used together with the correct and compatible genome (version, chromosome names, etc.)
Please try and let me know if you find any issues.
