### ISSUE TITLE
ftp server

### ISSUE THREAD

**Issue by akdemirlab** [hyounesy/ALEA#3]
Hi Hamid,

I am trying to download the test data using download_human_data.sh, however connection time is getting expired. 
Do you think the problem is with the connection or for some reason files in the ftp server are not reachable at the moment?

Thanks!
Kadir

**Comment by hyounesy** [comment]
Hello Kadir,
Looks like the files have either been removed from the host server or the access permissions have changed. I don't have access to the data server anymore so I will investigate and get back to you.
Alternatively if you have access to a public ftp server where I can upload the files (~10GB), I can upload them for you.
Best,
  Hamid

**Comment by akdemirlab** [comment]
Hey Hamid,

Could you please give me an email address so I can try to share a Box folder with you?

Thanks,
Kadir

**Comment by hyounesy** [comment]
Just checked and looks like the file are accessible again!
